spring:
  security:
    user:
      name: root
      password: 123
  datasource:
    url: jdbc:mysql://192.168.103.40:3306/smartcity_streetlight?characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    data-username: root
    data-password: mysql
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8001/eureka/
rabbitmq:
   host: localhost
   port: 5672
   username: root
   password: root      
      
